version: "3.9"
name: "Instodramat-dev"
services:
  keycloak_dev:
    image: jboss/keycloak
    container_name: keycloak_dev
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-instodramat.json
      - DB_VENDOR=mysql
      - DB_DATABASE=instodramat
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_ADDR=db_dev
      - JAVA_OPTS_APPEND=-Dkeycloak.profile.feature.upload_scripts=enabled
    volumes:
      - ./realm-instodramat.json:/tmp/realm-instodramat.json
    depends_on:
      db_dev:
        condition: service_healthy
  db_dev:
    image: mysql:latest
    container_name: db_dev
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=instodramat
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 10s
      timeout: 5s
      retries: 5